### ISSUE TITLE
Provide independent libraries or header files

### ISSUE THREAD

**Issue by romanholidaypancakes** [senator715/IDA-Fusion#1]
It is recommended that the signature generation engine be provided as a separate library (header file),make it available outside of ida, Example interface function:

```c++
std::string getSignature (void* addresss, long length);
```

**Comment by senator715** [comment]
Hello,

I'm not entirely sure if I plan to do this as of right now, the point of this project was really just to bring a proper signature scanner and creation plugin to IDA and I don't personally see any benefit for externalising this.

It would however be extremely easy to port the code from IDA's disassembler engine to something like HDE.
