### ISSUE TITLE
Doesnt work with ida 9

### ISSUE THREAD

**Issue by Koruptas** [senator715/IDA-Fusion#6]
I added the dlls to the plugin folder but i cant access the fusion sig finder

**Comment by senator715** [comment]
Hello,

What version exactly of IDA are you using?

**Comment by Koruptas** [comment]
Hello,

I am using version 9.0.240925.

**Comment by BadBrojo** [comment]
LoadLibrary(C:\Program Files\IDA Free 9.0\plugins\fusion.dll) error: The specified procedure could not be found.
C:\Program Files\IDA Free 9.0\plugins\fusion.dll: can't load file

LoadLibrary(C:\Program Files\IDA Free 9.0\plugins\fusion64.dll) error: The specified module could not be found.
C:\Program Files\IDA Free 9.0\plugins\fusion64.dll: can't load file

LoadLibrary(C:\Program Files\IDA Free 9.0\plugins\SigMaker9_64.dll) error: The specified module could not be found.
C:\Program Files\IDA Free 9.0\plugins\SigMaker9_64.dll: can't load file

version 9.0.240925.

:(

**Comment by Koruptas** [comment]
Where do you find this?

**Comment by Koruptas** [comment]
I solved the fusion plugin problem by downloading an older version of ida, but the other plugins dont work

**Comment by BadBrojo** [comment]
Can you provide the link you downloaded from, I tried digging up an older version, but hexrays revised their website, I couldn't find a viable link. Thanks in advance!

**Comment by Koruptas** [comment]
I use a "legal" one
